/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootImport } from './routes/_root'
import { Route as AuthImport } from './routes/_auth'
import { Route as RootIndexImport } from './routes/_root/index'
import { Route as RootAdminImport } from './routes/_root/_admin'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as RootAdminAdminImport } from './routes/_root/_admin/admin'

// Create/Update Routes

const RootRoute = RootImport.update({
  id: '/_root',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const RootIndexRoute = RootIndexImport.update({
  path: '/',
  getParentRoute: () => RootRoute,
} as any)

const RootAdminRoute = RootAdminImport.update({
  id: '/_admin',
  getParentRoute: () => RootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const RootAdminAdminRoute = RootAdminAdminImport.update({
  path: '/admin',
  getParentRoute: () => RootAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_root': {
      preLoaderRoute: typeof RootImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_root/_admin': {
      preLoaderRoute: typeof RootAdminImport
      parentRoute: typeof RootImport
    }
    '/_root/': {
      preLoaderRoute: typeof RootIndexImport
      parentRoute: typeof RootImport
    }
    '/_root/_admin/admin': {
      preLoaderRoute: typeof RootAdminAdminImport
      parentRoute: typeof RootAdminImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([AuthLoginRoute]),
  RootRoute.addChildren([
    RootAdminRoute.addChildren([RootAdminAdminRoute]),
    RootIndexRoute,
  ]),
])

/* prettier-ignore-end */
